// <auto-generated />
using System;
using LexumLinkApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexumLinkApp.Server.Migrations
{
    [DbContext(typeof(LexumLinkDbContext))]
    [Migration("20260910103334_AddClientSignUp")]
    partial class AddClientSignUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexumLinkApp.Server.Models.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllDay")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CaseId");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LodgementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MatterTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PrescriptionReminderStage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StaleNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StatutoryNoticeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SummonsServedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupervisorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MatterTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SupervisorUserId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.CaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseEvents");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.ClientClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountAwarded")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmountRequested")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RafReference")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.ClientRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalRequirements")
                        .HasColumnType("text");

                    b.Property<string>("AgreementSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientInitials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactAlternateNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactMobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPosition")
                        .HasColumnType("text");

                    b.Property<string>("ContactWhatsApp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclarationAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkedOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MonthlyServiceFee")
                        .HasColumnType("numeric");

                    b.Property<string>("NatureOfBusiness")
                        .HasColumnType("text");

                    b.Property<string>("PaymentDueOther")
                        .HasColumnType("text");

                    b.Property<string>("PaymentDuePreference")
                        .HasColumnType("text");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PopiaConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServicePackage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServicePackageOther")
                        .HasColumnType("text");

                    b.Property<string>("SignatureImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignedFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignedPosition")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradingName")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("VatNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedOrganizationId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("ClientRegistrations");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxClients")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StorageLimitGb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaseArchiveDays")
                        .HasColumnType("integer");

                    b.Property<int>("CaseIdleDays")
                        .HasColumnType("integer");

                    b.Property<int>("LockoutDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordMinLength")
                        .HasColumnType("integer");

                    b.Property<bool>("PasswordRequireNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("PasswordRequireSpecialChar")
                        .HasColumnType("boolean");

                    b.Property<bool>("PasswordRequireUppercase")
                        .HasColumnType("boolean");

                    b.Property<string>("SalesNotificationEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SmtpEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpFromEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpFromName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<bool>("SmtpUseStartTls")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PlatformSettings");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.PrescriptionMatterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DefaultPeriodMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MatterTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            DefaultPeriodMonths = 36,
                            IsActive = true,
                            Name = "Accident (RAF)",
                            Notes = "RAF Act s23: 3 years from date of accident, subject to lodgement requirements. Verify against current legislation.",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            DefaultPeriodMonths = 24,
                            IsActive = true,
                            Name = "Hit and run (unidentified vehicle)",
                            Notes = "RAF Act s17(1)(b): 2 years to lodge an unidentified-vehicle claim.",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            DefaultPeriodMonths = 24,
                            IsActive = true,
                            Name = "Carriage by air (baggage)",
                            Notes = "Montreal Convention Art 35: 2 years from date of arrival.",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            DefaultPeriodMonths = 24,
                            IsActive = true,
                            Name = "Carriage by air (cargo)",
                            Notes = "Montreal Convention Art 35: 2 years from date of arrival.",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            DefaultPeriodMonths = 24,
                            IsActive = true,
                            Name = "Carriage by air (delay)",
                            Notes = "Montreal Convention Art 35: 2 years from date of arrival.",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Name = "Sheriffs",
                            Notes = "Period depends on the specific claim against the sheriff — set the Prescription Date manually.",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Name = "Apportionment of Damages Act",
                            Notes = "Contribution claims are fact-dependent — set the Prescription Date manually.",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            DefaultPeriodMonths = 24,
                            IsActive = true,
                            Name = "Compensation for Occupational Injuries and Diseases Act 130 of 1993",
                            Notes = "Verify against COIDA and the specific claim (compensation claim vs. common-law employer claim).",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            DefaultPeriodMonths = 36,
                            IsActive = true,
                            Name = "Institution of Legal Proceedings Against Certain Organs of State Act 40 of 2002",
                            Notes = "3-year prescription; separately requires statutory notice within 6 months — capture via Statutory Notice Date.",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000a"),
                            DefaultPeriodMonths = 360,
                            IsActive = true,
                            Name = "Mortgage Bond / Judgment Debt / Taxation / Mine Minerals",
                            Notes = "Prescription Act s11(a): 30 years.",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000b"),
                            DefaultPeriodMonths = 180,
                            IsActive = true,
                            Name = "Debt Owed to State in Defined Circumstances",
                            Notes = "Prescription Act s11(a)(iii): 15 years — verify the debt falls into this category.",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000c"),
                            DefaultPeriodMonths = 72,
                            IsActive = true,
                            Name = "Debt from Bill of Exchange / Negotiable Instrument / Notarial Contract",
                            Notes = "Prescription Act s11(b): 6 years.",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000d"),
                            DefaultPeriodMonths = 36,
                            IsActive = true,
                            Name = "Any Other Debts / Civil Claims",
                            Notes = "Prescription Act s11(d): default 3 years for debts not otherwise specified.",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000e"),
                            IsActive = true,
                            Name = "Execution Against the Property of a Judgment Debtor",
                            Notes = "Procedural step, not a fixed prescription period — set the Prescription Date manually.",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000f"),
                            IsActive = true,
                            Name = "Review of Arbitration Awards (Labour Court)",
                            Notes = "LRA s145 review applications: strict 6-week deadline — set the Prescription Date manually.",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Name = "Arbitration Award Made an Order of the Labour Court",
                            Notes = "Enforcement timing is fact-dependent — set the Prescription Date manually.",
                            SortOrder = 16
                        });
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.CalendarEvent", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Case");

                    b.Navigation("Client");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Case", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.Client", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexumLinkApp.Server.Models.PrescriptionMatterType", "MatterType")
                        .WithMany()
                        .HasForeignKey("MatterTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany("Cases")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexumLinkApp.Server.Models.User", "SupervisorUser")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");

                    b.Navigation("Client");

                    b.Navigation("MatterType");

                    b.Navigation("Organization");

                    b.Navigation("SupervisorUser");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.CaseEvent", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.Case", "Case")
                        .WithMany("Events")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Client", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany("Clients")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.ClientClaim", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Case", "Case")
                        .WithMany("Claims")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany("Claims")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.ClientRegistration", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Organization", "LinkedOrganization")
                        .WithMany()
                        .HasForeignKey("LinkedOrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LexumLinkApp.Server.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedOrganization");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Document", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Case", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId");

                    b.HasOne("LexumLinkApp.Server.Models.Client", "Client")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId");

                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany("Documents")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexumLinkApp.Server.Models.User", "Uploader")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Case");

                    b.Navigation("Client");

                    b.Navigation("Organization");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Ticket", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany("Tickets")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexumLinkApp.Server.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Todo", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexumLinkApp.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.User", b =>
                {
                    b.HasOne("LexumLinkApp.Server.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Case", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Documents");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Client", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.Organization", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Claims");

                    b.Navigation("Clients");

                    b.Navigation("Documents");

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LexumLinkApp.Server.Models.User", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("UploadedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
